dict1 = {1:"a",2:"b",3:"c",4:"d"}
dict2 = dict(name = "John", age = 36, country = "Norway")
print(len(dict1))
print(dict1.get(1))
print(dict2.pop("age"))
print(dict1.popitem())
print(dict1.keys())
print(dict1.values())
print(dict1.items())
dict2.update({"color": "White"})
print(dict2)
cpy = dict1.copy()
print(cpy)
print(cpy.clear())